### ISSUE TITLE
Output icon only has 256 indexed colors palette versions

### ISSUE THREAD

**Issue by vHeemstra** [jtrauntvein/svg-to-ico#3]
I converted a SVG image using the script in the readme, but the output ICO file only contains versions in 256 indexed colors palette.

Is it possible to choose the bit depth with the sizes as well?

**Comment by jtrauntvein** [comment]
Internally, svg-to-ico uses the sharp package to do SVG parsing and image manipulation.  It looks like it does provide a toColourSpace() function that can be called on an image to change the colour model.  One of the options that can be included with that function is `"srgb"` but the documentation indicates that this is the default output if no other colour model is specified.

**Comment by vHeemstra** [comment]
Went down the ICO, BMP, PNG file format specification rabbit hole.. 😄  It seems the desktop application I was viewing the resulting ICO file in just could not handle the embedded PNG image (and showed them as 256-color bitmaps). This program uses Windows 32bpp RGBA bitmap format instead of PNG.

Anyway, this issue is not longer needed. Thanks for the quick response and the tool!
